---
branches:
  only:
    - master
language: ruby
bundler_args: --without development
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - 2.1.1
env:
  - PUPPET_VERSION="~> 3.0.0"
  - PUPPET_VERSION="~> 3.1.0"
  - PUPPET_VERSION="~> 3.2.0"
  - PUPPET_VERSION="~> 3.4.0"
matrix:
  exclude:
    - rvm: 2.1.1
      env: PUPPET_VERSION="~> 2.7.0"
    - rvm: 2.1.1
      env: PUPPET_VERSION="~> 3.0.0"
    - rvm: 2.1.1
      env: PUPPET_VERSION="~> 3.1.0"
    - rvm: 2.1.1
      env: PUPPET_VERSION="~> 3.2.0"

notifications:
  email:
    - stepan+travis_ci@stipl.net
