---
branches:
  only:
    - master
language: ruby
bundler_args: --without development
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - ruby-head
env:
  - PUPPET_VERSION="~> 2.7" RAKE_VERSION="~> 10.1"
  - PUPPET_VERSION="~> 3.0"
  - PUPPET_VERSION="~> 3.1"
  - PUPPET_VERSION="~> 3.2"
  - PUPPET_VERSION="~> 3.4"
notifications:
  email:
    - stepan+travis_ci@stipl.net
