name    'stepanstipl-stunnel'
version '0.1.0'
source 'git://github.com/stepanstipl/puppet-stunnel.git'
author 'Stepan Stipl'
license 'MIT License'
summary 'Puppet stunnel module'
description 'Puppet module for installing and configuring stunnel'
project_page 'https://github.com/stepanstipl/puppet-stunnel'

dependency 'puppetlabs/stdlib', '>= 3.1.0'
